spring.application.name=logging-demo
logging.level.root=INFO
logging.level.com.example.logging_demo=DEBUG
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n
logging.charset.console=UTF-8
spring.output.ansi.enabled=ALWAYS
